version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo Entered the install phase...
      - apt update  > /dev/null
      - npm install -g snyk > /dev/null
      - apt-get install -y maven > /dev/null
      - snyk config set api=$SnykToken
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - export snykurl=$(snyk monitor --all-projects | grep -o "https://[a-z0-9./-]*")
      - echo "{\"URL\"zz \"${snykurl}\"}" | sed "s/zz/:/g" > payload.json
      - snyk test --all-projects || echo vulnerabilities found
      - echo Snyk test completed on `date`
      - cat payload.json
      # - echo $LambdaName
      # - aws lambda invoke --function-name ${LambdaName} --payload $(base64 payload.json -w 10000)  response.json
      - echo "CodeArtifactRepository is $CodeArtifactRepository"
      - export CODEARTIFACT_URL=$(aws codeartifact get-repository-endpoint --domain $(echo $CodeArtifactRepository | awk -F'/' '{print $2}')  --repository $(echo $CodeArtifactRepository | awk -F'/' '{print $3}') --format maven --query 'repositoryEndpoint' --output text)
      - echo "CODEARTIFACT_URL is $CODEARTIFACT_URL"
      - export CODEARTIFACT_TOKEN=`aws codeartifact get-authorization-token --domain $(echo $CodeArtifactRepository | awk -F'/' '{print $2}') --query authorizationToken --output text`
      - echo $SNSTopicArn
      - aws sns publish --topic-arn ${SNSTopicArn} --subject "Snyk Dashboard URL" --message ${snykurl}
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      -  mvn -s settings.xml -Dmaven.test.failure.ignore=true clean package deploy > /dev/null
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
artifacts:  
  files:  
    # - target/*
    - payload.json




